# Generated by Django 5.0.6 on 2024-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("year", models.IntegerField()),
                ("electricity_access", models.FloatField()),
                ("cooking_fuel_access", models.FloatField()),
                ("renewable_electricity_capacity", models.FloatField()),
                ("fossil_fuel_electricity", models.FloatField()),
                ("nuclear_electricity", models.FloatField()),
                ("renewable_electricity", models.FloatField()),
                ("low_carbon_electricity", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
